name: AutoStudy

on:
  push:
    branches: [ master ]
  watch:
    types: [ started ]
  schedule:
    - cron: '20 18 * * 1,2'

jobs:
  autostudy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: 'set python'
      uses: actions/setup-python@v1
      with:
          python-version: '3.8'
    - name: 'install dependencies'
      run: python3 -m pip install --upgrade pip

    - name: 'install libs'
      run: pip3 install requests

    - name: startCheck
      env:
       nid: ${{ secrets.nid }}
       cardNo: ${{ secrets.cardNo }}
       openid: ${{ secrets.openid }}
       DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
       DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
       
      run: python3 main.py
